#!/bin/bash
# This script will take a .bib file and generate a publications page,
# sorted by year, for your github-pages site.
# HOW TO USE:
# 1. Update _/publications/publications.bib to most recent version
# 2. Run this script 'source render_pubs'

mv Gemfile Gemfile.bak
echo "source 'https://rubygems.org'" > Gemfile
echo "gem 'jekyll-scholar'" >> Gemfile

mkdir _plugins
echo "require 'jekyll/scholar'" > _plugins/ext.rb

HEADSTR=$'---\n---'
echo "$HEADSTR" | cat - pubs_gen.norender > pubs_gen.md 
echo "$HEADSTR" | cat - recent_pubs_gen.norender > recent_pubs_gen.md
bundle install
bundle show jekyll-scholar
bundle exec jekyll build

cat > _includes/pubs.html <_site/pubs_gen.html
cat > _includes/recent_pubs.html <_site/recent_pubs_gen.html
git checkout -- _config.yml
rm Gemfile Gemfile.lock pubs_gen.md recent_pubs_gen.md
rm -rf _plugins
mv Gemfile.bak Gemfile